backend:
  name: git-gateway
  branch: main
  # name: test-repo
# media_folder: content/images
# public_folder: /images
media_folder: /photos
public_folder: /photos
collections:
  - name: posts
    label: Posts
    folder: pages/posts
    # folder: content/posts
    create: true
    slug: '{{slug}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: text, required: false}
      - {label: Hero Image, name: hero_image, widget: image, required: false}
      - {label: Draft, name: draft, widget: boolean, required: false}
      - {label: Date, name: date, widget: datetime}
      - {label: Body, name: body, widget: markdown}
